# Generated by Django 5.1.1 on 2024-09-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financialasset',
            constraint=models.UniqueConstraint(fields=('ticker', 'type', 'market', 'exchange'), name='unique_asset'),
        ),
        migrations.AddConstraint(
            model_name='tradingpair',
            constraint=models.UniqueConstraint(fields=('base_asset', 'quote_asset'), name='unique_pair'),
        ),
    ]
