# Generated by Django 5.1.1 on 2024-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_financialasset_unique_asset_tradingpair_unique_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialasset',
            name='market',
            field=models.CharField(
                choices=[('SP', 'Спот'), ('FU', 'Фьючерсы'), ('OP', 'Опционы'), ('MA', 'Маржинальная торговля')],
                max_length=2,
                verbose_name='Рынок',
            ),
        ),
        migrations.AlterField(
            model_name='financialasset',
            name='type',
            field=models.CharField(
                choices=[('ST', 'Акция'), ('CR', 'Валюта'), ('CC', 'Криптовалюта')],
                max_length=2,
                verbose_name='Тип актива',
            ),
        ),
    ]
