# Generated by Django 5.1.1 on 2024-09-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                (
                    'interval',
                    models.CharField(
                        choices=[
                            ('1', '1 минута'),
                            ('3', '3 минуты'),
                            ('5', '5 минут'),
                            ('15', '15 минут'),
                            ('30', '30 минут'),
                            ('60', '1 час'),
                            ('120', '2 часа'),
                            ('240', '4 часа'),
                            ('360', '6 часов'),
                            ('720', '12 часов'),
                            ('D', '1 день'),
                            ('M', '1 месяц'),
                            ('W', '1 неделя'),
                        ],
                        max_length=3,
                        verbose_name='Интервал',
                    ),
                ),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена открытия')),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Наивысшая цена')),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Низшая цена')),
                (
                    'close_price',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Это последняя цена сделки, если свеча не закрыта.',
                        max_digits=20,
                        verbose_name='Цена закрытия',
                    ),
                ),
                (
                    'volume',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Для контрактов: количество контрактов. Для спотов: количество монет.',
                        max_digits=20,
                        verbose_name='Объем',
                    ),
                ),
                (
                    'turnover',
                    models.DecimalField(
                        decimal_places=8,
                        help_text='Единица измерения: количество квотируемых монет.',
                        max_digits=20,
                        verbose_name='Оборот',
                    ),
                ),
                (
                    'pair',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='Klines',
                        to='accounting.tradingpair',
                        verbose_name='Торговая пара',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Бар',
                'verbose_name_plural': 'Бары',
            },
        ),
    ]
